# version: "3.9"
services:
  backend:
    build:
      context: ../../backend/
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ../../frontend/
      args:
        - API_URL=http://localhost:8000
    depends_on:
      - backend
    ports:
      - "8080:80"
